const countries = [
"ANGOLA",
"ARGELIA",
"BENIN",
"BOTSUANA",
"BURKINA FASO",
"BURUNDI",
"CABO VERDE",
"CAMERÚN",
"CHAD",
"COMORAS",
"COSTA DE MARFIL",
"EGIPTO",
"ERITREA",
"ETIOPÍA",
"GABÓN",
"GAMBIA",
"GHANA",
"GUINEA",
"GUINEA ECUATORIAL",
"GUINEA-BISSAU",
"KENIA",
"LESOTO",
"LIBERIA",
"LIBIA",
"MADAGASCAR",
"MALAUI",
"MALI",
"MARRUECOS",
"MAURICIO",
"MAURITANIA",
"MOZAMBIQUE",
"NAMIBIA",
"NÍGER",
"NIGERIA",
"REPÚBLICA CENTROAFRICANA",
"REPÚBLICA DEL CONGO",
"REPÚBLICA DEMOCRÁTICA DEL CONGO",
"RUANDA",
"SANTO TOMÉ Y PRÍNCIPE",
"SENEGAL",
"SEYCHELLES",
"SIERRA LEONA",
"SOMALIA",
"SUAZILANDIA",
"SUDÁFRICA",
"SUDÁN",
"SUDÁN DEL SUR",
"TANZANIA",
"TOGO",
"TÚNEZ",
"UGANDA",
"YIBUTI",
"ZAMBIA",
"ZIMBABUE",
"ANTIGUA Y BARBUDA",
"ARGENTINA",
"BAHAMAS",
"BARBADOS",
"BELICE",
"BOLIVIA",
"BRASIL",
"CANADÁ",
"CHILE",
"COLOMBIA",
"COSTA RICA",
"CUBA",
"DOMINICA",
"ECUADOR",
"EL SALVADOR",
"ESTADOS UNIDOS",
"GRANADA",
"GUATEMALA",
"GUYANA",
"HAITÍ",
"HONDURAS",
"JAMAICA",
"MÉXICO",
"NICARAGUA",
"PANAMÁ",
"PARAGUAY",
"PERÚ",
"PUERTO RICO",
"REPÚBLICA DOMINICANA",
"SAN CRISTÓBAL Y NIEVES",
"SAN VICENTE Y LAS GRANADINAS",
"SANTA LUCÍA",
"SURINAM",
"TRINIDAD Y TOBAGO",
"URUGUAY",
"VENEZUELA",
"AFGANISTÁN",
"ARABIA SAUDITA",
"BANGLADÉS",
"BARÉIN",
"BRUNEI",
"BUTÁN",
"CAMBOYA",
"CATAR",
"CHINA",
"CHIPRE",
"COREA DEL NORTE",
"COREA DEL SUR",
"EMIRATOS ARABES UNIDOS",
"FILIPINAS",
"INDIA",
"INDONESIA",
"IRÁN",
"IRAQ",
"ISRAEL",
"JAPÓN",
"JORDANIA",
"KAZAJISTÁN",
"KIRGUISTÁN",
"KUWAIT",
"LAOS",
"LÍBANO",
"MALASIA",
"MALDIVAS",
"MONGOLIA",
"MYANMAR (BIRMANIA)",
"NEPAL",
"OMÁN",
"PAKISTÁN",
"PALESTINA",
"SIRIA",
"SRI LANKA",
"TAILANDIA",
"TAYIKISTÁN",
"TIMOR ORIENTAL",
"TURKMENISTÁN",
"TURQUÍA",
"UZBEKISTÁN",
"VIETNAM",
"YEMEN",
"ALBANIA",
"ALEMANIA",
"ANDORRA",
"ARMENIA",
"AUSTRIA",
"AZERBAIYÁN",
"BÉLGICA",
"BIELORRUSIA",
"BOSNIA Y HERZEGOVINA",
"BULGARIA",
"CROACIA",
"DINAMARCA",
"ESLOVAQUIA",
"ESLOVENIA",
"ESPAÑA",
"ESTONIA",
"FINLANDIA",
"FRANCIA",
"GEORGIA",
"GRECIA",
"HUNGRÍA",
"IRLANDA",
"ISLANDIA",
"ITALIA",
"LETONIA",
"LIECHTENSTEIN",
"LITUANIA",
"LUXEMBURGO",
"MALTA",
"MOLDAVIA",
"MÓNACO",
"MONTENEGRO",
"NORUEGA",
"PAÍSES BAJOS",
"POLONIA",
"PORTUGAL",
"REINO UNIDO",
"REPÚBLICA CHECA",
"REPÚBLICA DE MACEDONIA",
"RUMANIA",
"RUSIA",
"SAN MARINO",
"SERBIA",
"SUECIA",
"SUIZA",
"UCRANIA",
"AUSTRALIA",
"FIYI",
"ISLAS MARSHALL",
"ISLAS SALOMÓN",
"KIRIBATI",
"MICRONESIA",
"NAURU",
"NUEVA ZELANDA",
"PALAOS",
"PAPÚA NUEVA GUINEA",
"SAMOA",
"TONGA",
"TUVALU",
"VANUATU"
];

const countriesBeginningWithE = 
[
"EGIPTO",
"ERITREA",
"ETIOPÍA",
"ECUADOR",
"EL SALVADOR",
"ESTADOS UNIDOS",
"EMIRATOS ARABES UNIDOS",
"ESLOVAQUIA",
"ESLOVENIA",
"ESPAÑA",
"ESTONIA"
];

const countriesBeginningWithF = 
[
"FILIPINAS",
"FINLANDIA",
"FRANCIA",
"FIYI"
];

const numbers = [1,2,3,4,5,6,7,8,9,10];

const shoppingCart = [
  { category: "Frutas y Verduras", product: "Lechuga", price: 0.8, units: 1 },
  { category: "Carne y Pescado", product: "Pechuga pollo", price: 3.75, units: 2 },
  { category: "Droguería", product: "Gel ducha", price: 1.15, units: 1 },
  { category: "Droguería", product: "Papel cocina", price: 0.9, units: 3 },
  { category: "Frutas y Verduras", product: "Sandía", price: 4.65, units: 1 },
  { category: "Frutas y Verduras", product: "Puerro", price: 4.65, units: 2 },
  { category: "Carne y Pescado", product: "Secreto ibérico", price: 5.75, units: 2 },
];

const stringToConcatenate = 
[
  "hola,",
  "hola",
  "comienza",
  "tiempo de juego"
];

const users = [{
    "id": 1,
    "first_name": "Herminia",
    "last_name": "Sexon"
  }, {
    "first_name": "Prinz",
    "last_name": "Applegarth",
  }, {
    "id": 2,
    "first_name": "Huntlee",
    "last_name": "Issacoff"
  }, {
    "first_name": "Jacinthe",
    "last_name": "Olorenshaw"
  }, {
    "id": 3,
    "first_name": "Vlad",
    "last_name": "Denyagin"
}];

export {countries, countriesBeginningWithE, countriesBeginningWithF, numbers, shoppingCart, stringToConcatenate, users};
